# Generated by Django 4.0.4 on 2022-05-21 19:35

from django.db import migrations

from polls.demo_data import DEFAULT_QUESTIONS


def up(apps, schema_editor):
    Question = apps.get_model("polls", "Question")
    Answer = apps.get_model("polls", "Answer")

    for q_subject, answers in DEFAULT_QUESTIONS.items():
        q, created = Question.objects.get_or_create(subject=q_subject)
        for a in answers:
            Answer.objects.get_or_create(question=q, subject=a)


def down(apps, schema_editor):
    Question = apps.get_model("polls", "Question")

    for q_subject in DEFAULT_QUESTIONS.keys():
        Question.objects.filter(subject=q_subject).delete()
    # Cascade should remove the answers


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_rename_vote_time_vote_created_at_answer_created_at_and_more"),
    ]

    operations = [migrations.RunPython(up, down)]
