# Generated by Django 4.0.4 on 2022-05-23 01:42

from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0005_answer_image_answer_image_height_answer_image_width"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="image",
            field=models.ImageField(
                blank=True,
                height_field="image_height",
                null=True,
                upload_to=polls.models.answer_image_upload_to,
                width_field="image_width",
            ),
        ),
    ]
